# Generated by Django 4.2.5 on 2023-10-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_active_author_biography_author_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
